import type { Product } from "./types";

// Catálogo inicial confirmado; não contém histórico operacional.

const CATALOG_PRODUCTS: Product[] = [
  {
    id: "hamb-trad",
    name: "Hambúrguer tradicional",
    category: "Hambúrgueres",
    price: 9.99,
    stock: 0,
    minimum: 0,
    emoji: "🍔",
  },
  {
    id: "hamb-art",
    name: "Hambúrguer artesanal",
    category: "Hambúrgueres",
    price: 14.99,
    stock: 0,
    minimum: 0,
    emoji: "🍔",
  },
  {
    id: "xbacon-trad",
    name: "X-Bacon tradicional",
    category: "Hambúrgueres",
    price: 14.99,
    stock: 0,
    minimum: 0,
    emoji: "🥓",
  },
  {
    id: "xbacon-art",
    name: "X-Bacon artesanal",
    category: "Hambúrgueres",
    price: 19.99,
    stock: 0,
    minimum: 0,
    emoji: "🥓",
  },
  {
    id: "xcalabresa-trad",
    name: "X-Calabresa tradicional",
    category: "Hambúrgueres",
    price: 14.99,
    stock: 0,
    minimum: 0,
    emoji: "🌭",
  },
  {
    id: "xcalabresa-art",
    name: "X-Calabresa artesanal",
    category: "Hambúrgueres",
    price: 19.99,
    stock: 0,
    minimum: 0,
    emoji: "🌭",
  },
  {
    id: "xcheddar-trad",
    name: "X-Cheddar tradicional",
    category: "Hambúrgueres",
    price: 14.99,
    stock: 0,
    minimum: 0,
    emoji: "🧀",
  },
  {
    id: "xcheddar-art",
    name: "X-Cheddar artesanal",
    category: "Hambúrgueres",
    price: 19.99,
    stock: 0,
    minimum: 0,
    emoji: "🧀",
  },
  {
    id: "xtudo-trad",
    name: "X-Tudo tradicional",
    category: "Hambúrgueres",
    price: 19.99,
    stock: 0,
    minimum: 0,
    emoji: "🍔",
  },
  {
    id: "xtudo-art",
    name: "X-Tudo artesanal",
    category: "Hambúrgueres",
    price: 24.99,
    stock: 0,
    minimum: 0,
    emoji: "🍔",
  },
  {
    id: "pastel",
    name: "Pastel",
    category: "Salgados",
    price: 9,
    stock: 0,
    minimum: 0,
    emoji: "🥟",
  },
  {
    id: "coxinha",
    name: "Coxinha",
    category: "Salgados",
    price: 5,
    stock: 0,
    minimum: 0,
    emoji: "🍗",
  },
  {
    id: "cachorro",
    name: "Cachorro-quente",
    category: "Salgados",
    price: 7,
    stock: 0,
    minimum: 0,
    emoji: "🌭",
  },
  {
    id: "bolo",
    name: "Bolo",
    category: "Sobremesas",
    price: 7,
    stock: 0,
    minimum: 0,
    emoji: "🍰",
  },
  {
    id: "batata",
    name: "Batata frita 400 g",
    category: "Petiscos",
    price: 10,
    stock: 0,
    minimum: 0,
    emoji: "🍟",
  },
  {
    id: "batata-americana",
    name: "Batata cheddar e bacon",
    category: "Petiscos",
    price: 13,
    stock: 0,
    minimum: 0,
    emoji: "🍟",
  },
  {
    id: "carne-fritas",
    name: "Carne com fritas",
    category: "Petiscos",
    price: 35,
    stock: 0,
    minimum: 0,
    emoji: "🥩",
  },
  {
    id: "camarao-fritas",
    name: "Camarão com fritas",
    category: "Petiscos",
    price: 35,
    stock: 0,
    minimum: 0,
    emoji: "🍤",
  },
  {
    id: "picole",
    name: "Picolé gourmet",
    category: "Sobremesas",
    price: 3,
    stock: 0,
    minimum: 0,
    emoji: "🍦",
  },
  {
    id: "sobremesa-200",
    name: "Sobremesa gelada 200 g",
    category: "Sobremesas",
    price: 5,
    stock: 0,
    minimum: 0,
    emoji: "🍧",
  },
  {
    id: "sobremesa-500",
    name: "Sobremesa gelada 500 g",
    category: "Sobremesas",
    price: 11,
    stock: 0,
    minimum: 0,
    emoji: "🍧",
  },
  {
    id: "moreninha",
    name: "Moreninha",
    category: "Sobremesas",
    price: 4,
    stock: 0,
    minimum: 0,
    emoji: "🍫",
  },
  {
    id: "sundae",
    name: "Sundae",
    category: "Sobremesas",
    price: 5,
    stock: 0,
    minimum: 0,
    emoji: "🍨",
  },
  {
    id: "guaracai",
    name: "Guaraçaí / Guaraná do Amazonas 500 ml",
    category: "Sobremesas",
    price: 8,
    stock: 0,
    minimum: 0,
    emoji: "🥤",
  },
  {
    id: "suco",
    name: "Suco da polpa",
    category: "Bebidas",
    price: 6,
    stock: 0,
    minimum: 0,
    emoji: "🥤",
  },
  {
    id: "coca-lata",
    name: "Coca-Cola lata",
    category: "Bebidas",
    price: 6,
    stock: 0,
    minimum: 0,
    emoji: "🥤",
  },
  {
    id: "refri-lata",
    name: "Refrigerante lata",
    category: "Bebidas",
    price: 5,
    stock: 0,
    minimum: 0,
    emoji: "🥤",
  },
  {
    id: "agua",
    name: "Água mineral",
    category: "Bebidas",
    price: 2,
    stock: 0,
    minimum: 0,
    emoji: "💧",
  },
  {
    id: "coca-1l",
    name: "Coca-Cola LS 1L",
    category: "Bebidas",
    price: 8.5,
    stock: 0,
    minimum: 0,
    emoji: "🍶",
  },
  {
    id: "guarana-1l",
    name: "Guaraná 1 L",
    category: "Bebidas",
    price: 8,
    stock: 0,
    minimum: 0,
    emoji: "🍶",
  },
  {
    id: "brahma-litrao",
    name: "Brahma litrão",
    category: "Bebidas",
    price: 10,
    stock: 0,
    minimum: 0,
    emoji: "🍺",
  },
  {
    id: "schin-litrao",
    name: "Schin litrão",
    category: "Bebidas",
    price: 7,
    stock: 0,
    minimum: 0,
    emoji: "🍺",
  },
  {
    id: "guarana-caculinha",
    name: "Guaraná caçulinha",
    category: "Bebidas",
    price: 2,
    stock: 0,
    minimum: 0,
    emoji: "🥤",
  },
  {
    id: "embalagem",
    name: "Embalagem para viagem",
    category: "Adicionais",
    price: 1,
    stock: 0,
    minimum: 0,
    emoji: "🥡",
  },
];

// O cardápio e os preços vieram das referências fornecidas. Quantidades e
// limites de estoque só podem ser informados pela proprietária no primeiro uso.
export const INITIAL_PRODUCTS: Product[] = CATALOG_PRODUCTS.map((product) => ({
  ...product,
  stock: 0,
  minimum: 0,
}));
