import type { Expense, Product, Sale } from "./types";

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "hamb-trad",
    name: "Hambúrguer tradicional",
    category: "Hambúrgueres",
    price: 9.99,
    stock: 32,
    minimum: 12,
    emoji: "🍔",
  },
  {
    id: "hamb-art",
    name: "Hambúrguer artesanal",
    category: "Hambúrgueres",
    price: 14.99,
    stock: 18,
    minimum: 10,
    emoji: "🍔",
  },
  {
    id: "xbacon-trad",
    name: "X-Bacon tradicional",
    category: "Hambúrgueres",
    price: 14.99,
    stock: 14,
    minimum: 8,
    emoji: "🥓",
  },
  {
    id: "xbacon-art",
    name: "X-Bacon artesanal",
    category: "Hambúrgueres",
    price: 19.99,
    stock: 11,
    minimum: 8,
    emoji: "🥓",
  },
  {
    id: "xcalabresa-trad",
    name: "X-Calabresa tradicional",
    category: "Hambúrgueres",
    price: 14.99,
    stock: 17,
    minimum: 8,
    emoji: "🌭",
  },
  {
    id: "xcalabresa-art",
    name: "X-Calabresa artesanal",
    category: "Hambúrgueres",
    price: 19.99,
    stock: 13,
    minimum: 8,
    emoji: "🌭",
  },
  {
    id: "xcheddar-trad",
    name: "X-Cheddar tradicional",
    category: "Hambúrgueres",
    price: 14.99,
    stock: 11,
    minimum: 8,
    emoji: "🧀",
  },
  {
    id: "xcheddar-art",
    name: "X-Cheddar artesanal",
    category: "Hambúrgueres",
    price: 19.99,
    stock: 10,
    minimum: 8,
    emoji: "🧀",
  },
  {
    id: "xtudo-trad",
    name: "X-Tudo tradicional",
    category: "Hambúrgueres",
    price: 19.99,
    stock: 9,
    minimum: 8,
    emoji: "🍔",
  },
  {
    id: "xtudo-art",
    name: "X-Tudo artesanal",
    category: "Hambúrgueres",
    price: 24.99,
    stock: 8,
    minimum: 8,
    emoji: "🍔",
  },
  {
    id: "pastel",
    name: "Pastel",
    category: "Salgados",
    price: 9,
    stock: 28,
    minimum: 10,
    emoji: "🥟",
  },
  {
    id: "coxinha",
    name: "Coxinha",
    category: "Salgados",
    price: 5,
    stock: 22,
    minimum: 12,
    emoji: "🍗",
  },
  {
    id: "cachorro",
    name: "Cachorro-quente",
    category: "Salgados",
    price: 7,
    stock: 16,
    minimum: 8,
    emoji: "🌭",
  },
  {
    id: "bolo",
    name: "Bolo",
    category: "Sobremesas",
    price: 7,
    stock: 12,
    minimum: 5,
    emoji: "🍰",
  },
  {
    id: "batata",
    name: "Batata frita 400 g",
    category: "Petiscos",
    price: 10,
    stock: 19,
    minimum: 8,
    emoji: "🍟",
  },
  {
    id: "batata-americana",
    name: "Batata cheddar e bacon",
    category: "Petiscos",
    price: 13,
    stock: 12,
    minimum: 6,
    emoji: "🍟",
  },
  {
    id: "carne-fritas",
    name: "Carne com fritas",
    category: "Petiscos",
    price: 35,
    stock: 8,
    minimum: 5,
    emoji: "🥩",
  },
  {
    id: "camarao-fritas",
    name: "Camarão com fritas",
    category: "Petiscos",
    price: 35,
    stock: 7,
    minimum: 5,
    emoji: "🍤",
  },
  {
    id: "picole",
    name: "Picolé gourmet",
    category: "Sobremesas",
    price: 3,
    stock: 24,
    minimum: 10,
    emoji: "🍦",
  },
  {
    id: "sobremesa-200",
    name: "Sobremesa gelada 200 g",
    category: "Sobremesas",
    price: 5,
    stock: 18,
    minimum: 8,
    emoji: "🍧",
  },
  {
    id: "sobremesa-500",
    name: "Sobremesa gelada 500 g",
    category: "Sobremesas",
    price: 11,
    stock: 12,
    minimum: 6,
    emoji: "🍧",
  },
  {
    id: "moreninha",
    name: "Moreninha",
    category: "Sobremesas",
    price: 4,
    stock: 16,
    minimum: 8,
    emoji: "🍫",
  },
  {
    id: "sundae",
    name: "Sundae",
    category: "Sobremesas",
    price: 5,
    stock: 14,
    minimum: 6,
    emoji: "🍨",
  },
  {
    id: "guaracai",
    name: "Guaraçaí / Guaraná do Amazonas 500 ml",
    category: "Sobremesas",
    price: 8,
    stock: 12,
    minimum: 6,
    emoji: "🥤",
  },
  {
    id: "suco",
    name: "Suco da polpa",
    category: "Bebidas",
    price: 6,
    stock: 14,
    minimum: 8,
    emoji: "🥤",
  },
  {
    id: "coca-lata",
    name: "Coca-Cola lata",
    category: "Bebidas",
    price: 6,
    stock: 6,
    minimum: 10,
    emoji: "🥤",
  },
  {
    id: "refri-lata",
    name: "Refrigerante lata",
    category: "Bebidas",
    price: 5,
    stock: 9,
    minimum: 10,
    emoji: "🥤",
  },
  {
    id: "agua",
    name: "Água mineral",
    category: "Bebidas",
    price: 2,
    stock: 18,
    minimum: 10,
    emoji: "💧",
  },
  {
    id: "coca-1l",
    name: "Coca-Cola LS 1L",
    category: "Bebidas",
    price: 8.5,
    stock: 8,
    minimum: 6,
    emoji: "🍶",
  },
  {
    id: "guarana-1l",
    name: "Guaraná 1 L",
    category: "Bebidas",
    price: 8,
    stock: 7,
    minimum: 8,
    emoji: "🍶",
  },
  {
    id: "brahma-litrao",
    name: "Brahma litrão",
    category: "Bebidas",
    price: 10,
    stock: 10,
    minimum: 6,
    emoji: "🍺",
  },
  {
    id: "schin-litrao",
    name: "Schin litrão",
    category: "Bebidas",
    price: 7,
    stock: 10,
    minimum: 6,
    emoji: "🍺",
  },
  {
    id: "guarana-caculinha",
    name: "Guaraná caçulinha",
    category: "Bebidas",
    price: 2,
    stock: 18,
    minimum: 10,
    emoji: "🥤",
  },
  {
    id: "embalagem",
    name: "Embalagem para viagem",
    category: "Adicionais",
    price: 1,
    stock: 40,
    minimum: 15,
    emoji: "🥡",
  },
];

export function createDemoSales(): Sale[] {
  const now = Date.now();
  return [
    {
      id: "PV-1048",
      timestamp: now - 14 * 60_000,
      total: 29.98,
      payment: "Pix",
      items: [
        {
          productId: "xbacon-trad",
          name: "X-Bacon tradicional",
          price: 14.99,
          quantity: 2,
        },
      ],
    },
    {
      id: "PV-1047",
      timestamp: now - 33 * 60_000,
      total: 31,
      payment: "Dinheiro",
      items: [
        {
          productId: "pastel",
          name: "Pastel",
          price: 9,
          quantity: 1,
        },
        {
          productId: "batata",
          name: "Batata frita 400 g",
          price: 10,
          quantity: 1,
        },
        {
          productId: "coca-lata",
          name: "Coca-Cola lata",
          price: 6,
          quantity: 2,
        },
      ],
    },
    {
      id: "PV-1046",
      timestamp: now - 57 * 60_000,
      total: 41,
      payment: "Cartão",
      items: [
        {
          productId: "carne-fritas",
          name: "Carne com fritas",
          price: 35,
          quantity: 1,
        },
        {
          productId: "suco",
          name: "Suco da polpa",
          price: 6,
          quantity: 1,
        },
      ],
    },
    {
      id: "PV-1045",
      timestamp: now - 91 * 60_000,
      total: 24.99,
      payment: "Pix",
      items: [
        {
          productId: "xtudo-trad",
          name: "X-Tudo tradicional",
          price: 19.99,
          quantity: 1,
        },
        {
          productId: "refri-lata",
          name: "Refrigerante lata",
          price: 5,
          quantity: 1,
        },
      ],
    },
  ];
}

export function createDemoExpenses(): Expense[] {
  return [
    {
      id: "DS-204",
      timestamp: Date.now() - 73 * 60_000,
      description: "Compra de pão e verduras",
      category: "Matéria-prima",
      amount: 38,
      payment: "Dinheiro",
    },
  ];
}

